In [2]:
#1import required libraries
import pandas as pd 
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.metrics import accuracy_score

In [3]:
#3 load 20 news grp train subset
train_df = pd.read_csv("newsgroups_train.csv")
train_df.head(5)

text  target       category
0  From: degroff@netcom.com (21012d)\nSubject: Re...       2      sci.space
1  From: ab@nova.cc.purdue.edu (Allen B)\nSubject...       1  comp.graphics
2  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...       0    alt.atheism
3  From: capelli@vnet.IBM.COM (Ron Capelli)\nSubj...       1  comp.graphics
4  From: henry@zoo.toronto.edu (Henry Spencer)\nS...       2      sci.space

In [4]:
#4 load 20 news grp test subset
test_df = pd.read_csv("newsgroups_test.csv")
test_df.head(5)

text  target       category
0  From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1  From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2  From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3  From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4  From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics

In [5]:
test_df.columns

Index(['text', 'target', 'category'], dtype='object')

In [6]:
#5 .print target labels
print(train_df['category'].unique())
print(test_df['category'].unique())

['sci.space' 'comp.graphics' 'alt.atheism']
['sci.space' 'comp.graphics' 'alt.atheism']


In [7]:
train_df.columns

Index(['text', 'target', 'category'], dtype='object')

In [8]:
train_df.iloc[0,0]

'From: degroff@netcom.com (21012d)\nSubject: Re: Venus Lander for Venus Conditions.\nOrganization: Netcom Online Communications Services (408-241-9760 login: guest)\nLines: 8\n\n\n  I doubt there are good prospects for  a self armoring system\nfor venus surface conditions (several hundred degrees, very high\npressure of CO2, possibly sulfuric and nitric acids or oxides\nbut it is a notion to consider for outer planets rs where you might\npick up ices under less extream upper atmosphere conditions buying\ndeeper penetration.  A nice creative idea, unlikly but worthy of\nthinking about.\n'

In [9]:
test_df.iloc[1,0]

'From: "Changyaw Wang" <wangc@cs.indiana.edu>\nSubject: Re: 3d graphics software company info?\nOrganization: Computer Science, Indiana University\nLines: 6\n\nI believe many people will be happy to have this information.   So, \nplease post it to the comp.graphics.\n\nThanks,\n-Changyaw\n\n'

In [10]:
#10. print news training data of 5th article
#print("5th article :",train_df['text'].iloc[4])
print(train_df.iloc[4,0])

From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: TRUE "GLOBE", Who makes it?
Organization: U of Toronto Zoology
Lines: 12

In article <bill.047m@xpresso.UUCP> bill@xpresso.UUCP (Bill Vance) writes:
>It has been known for quite a while that the earth is actually more pear
>shaped than globular/spherical.  Does anyone make a "globe" that is accurate
>as to actual shape, landmass configuration/Long/Lat lines etc.?

I don't think you're going to be able to see the differences from a sphere
unless they are greatly exaggerated.  Even the equatorial bulge is only
about 1 part in 300 -- you'd never notice a 1mm error in a 30cm globe --
and the other deviations from spherical shape are much smaller.
-- 
SVR4 resembles a high-speed collision   | Henry Spencer @ U of Toronto Zoology
between SVR3 and SunOS.    - Dick Dunn  |  henry@zoo.toronto.edu  utzoo!henry



In [11]:
#11 . print shape of data and targets
print(train_df.shape)
print(test_df.shape)

(1657, 3)
(1102, 3)


In [12]:
#13. By using count vectorizor train data into numrical format considering  
docs = train_df['text']
vct = CountVectorizer()
X = vct.fit_transform(docs)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
#14 .use bernoulli for training
x = X
y = train_df['target']
model = BernoulliNB()
#model = GaussianNB()
#model = MultinomialNB()
model.fit(x,y)

BernoulliNB()

In [14]:
train_df.shape

(1657, 3)

In [15]:
test_df.shape

(1102, 3)

In [16]:
y_pred = model.predict(x)
print("y_pred :",y_pred)
accuracy = accuracy_score(y,y_pred)
print("accuracy:",accuracy)

y_pred : [2 1 1 ... 1 1 2]
accuracy: 0.9414604707302353


In [17]:
#15  byusing countvectorizer convert test data into numeric format
test_docs = test_df['text']
vct1 = CountVectorizer()
X1 = vct1.fit_transform(test_docs)
print(X1.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
#16 .predict target labels  for testing set
#17 find accuracy score on test set
x_test = X1
y_test = test_df['target']
model = BernoulliNB()
model.fit(x_test,y_test)
y_predict = model.predict(x_test)
acc = accuracy_score(y_test,y_predict)
print("accuaracy : ",acc)
print("y_pred : ",y_predict)

accuaracy :  0.9745916515426497
y_pred :  [2 1 1 ... 0 1 2]


In [19]:
#18. used Tfidfvectorizer instead of count vectorizer and use multinomial NB
test_docs = test_df['text']
vct2 = TfidfVectorizer()
X2 = vct2.fit_transform(test_docs)
print(X2.toarray())


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.07468346 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [20]:
#19. find test set accuracy
x_test1 = X1
y_test1 = test_df['target']
model = MultinomialNB()
model.fit(x_test1,y_test1)
y_predict1 = model.predict(x_test1)
print("y_predict1 :", y_predict1)
acc1 = accuracy_score(y_test1,y_predict1)
print("accuracy1 : ",acc1)

y_predict1 : [2 1 1 ... 0 1 2]
accuracy1 :  0.9936479128856625


In [21]:
doc2 = 'From: lioness@maple.circa.ufl.edu\nSubject: Te...'


# Transform test data (pass as a list)
test_record = vectorizer.transform([doc2])

# Predict
a = model.predict(test_record)
print(a[0]) 

NameError: name 'vectorizer' is not defined